name: Issues Report / 问题反馈
description: "Feedback, report one or more issues / 反馈，报告一个或一些问题"
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your testing  
        感谢您的测试
  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist / 检查项"
      description: "Please review the following items carefully and confirm / 请仔细核对以下项目并确认"
      options:
        - label: "I have searched the Issues page and confirmed that this bug has not been previously submitted / 我已在Issues页面搜索并确认该bug未曾被提交过"
        - label: "I have made every effort to confirm that this issue was not caused by me / 我已尽量确认该错误并未我导致"
          required: true
  - type: textarea
    id: error
    attributes:
      label: "Describe the bug / 描述错误"
      description: "在这里简要描述出现的错误或存在的问题"
      placeholder: "支持Markdown语法"
      value: "text"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs or Screenshoots (optional) / 日志或屏幕截图 (可选)"
      description: "Drop your logs or screenshots here (optional) / 将你的日志或屏幕截图拖拽并复制在这里 (可选)"
      render: shell
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "Modpack version channel / 整合包版本通道"
      description: "Select the version where the issues occurred from the dropdown menu below / 在下方下拉菜单中选择错误所在的版本"
      options:
        - Playing Testing Version
        - Modified Version
      default: 1
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: "Issues category / 错误类别"
      description: "Select the category of the issue you want to submit from the dropdown menu below / 在下方下拉菜单中选择你要提交的问题分类本"
      options:
        - "I submitted multiple different types of errors all at once / 我一次性提交了多个不同种类的错误"
        - "Shaders or Resources"
        - "Mods bug"
        - "Mechanism defect"
        - "Game Crashed or cannot Launched"
        - "others"
      default: 1
    validations:
      required: true
