name: Issues Report
description: Issues Report
title: "[Bug]: "
labels: ["bug"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your testing  
        感谢您的测试
  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist / 检查项"
      description: "Please review the following items carefully and confirm / 请仔细核对以下项目并确认"
      options:
        - label: "I have searched the Issues page and confirmed that this bug has not been previously submitted / 我已在Issues页面搜索并确认该bug未曾被提交过"
        - label: "I have made every effort to confirm that this issue was not caused by me / 我已尽量确认该错误并未我导致"
          required: true
  - type: textarea
    id: error
    attributes:
      label: "Describe the bug / 描述错误"
      description: "在这里简要描述出现的错误或存在的问题"
      placeholder: "悬浮字符测试"
      value: "text"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs or Screenshoots (optional) / 日志或屏幕截图 (可选)"
      description: "Drop your logs or screenshots here (optional) / 将你的日志或屏幕截图拖拽并复制在这里 (可选)"
      render: shell
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "Your modpack version channel / 你的整合包版本通道"
      description: "Select the version in which you encountered the issue below / 在下方选择你从中发现问题的版本"
      options:
        - Playing Testing Version
        - Modified Version
      default: 1
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: "Notes (optional) / 备注 (可选)"
      description: "text below"
    validations:
      required: true
